feature: Add select to Calendar, change Select
anastasiya-nd/budget pull request #20
Opened 2021-09-06 19:52 UTC by anastasiya-nd

2021-09-07 05:03 UTC, ok2ju requested changes

2021-09-07 05:03 UTC, ok2ju commented on src/components/Calendar/utils.js
> +  for (let i = startingYear; i <= endingYear; i++) { // eslint-disable-line
I found more interesting way to do it:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#sequence_generator_range

2021-09-07 05:03 UTC, ok2ju commented on src/components/Select/Select.jsx
> +    return chooseOption(option);
Why this func return function call?

2021-09-08 11:48 UTC, anastasiya-nd commented on src/components/Calendar/utils.js
> +export const getMonthIndex = (month, monthNames) => monthNames.indexOf(month);
monthNames is constant

2021-09-08 11:52 UTC, anastasiya-nd commented on src/components/Calendar/utils.js
> +export const getDateFromMonthSelect = (date, month) => new Date(date.getFullYear(), month, 1);
I don't get first day. I have to get days for rendering calendar. I choose month in Select and I get days for this calendar

2021-09-08 16:00 UTC, anastasiya-nd commented on src/components/Calendar/utils.js
> +export const getMonthIndex = (month, monthNames) => monthNames.indexOf(month);
> Should `monthNames` be a constant?

I don't understand what I have to do.
I have to do import monthNames in utils?

2021-09-09 05:55 UTC, ok2ju requested changes

2021-09-09 05:55 UTC, ok2ju commented on src/components/Select/Select.jsx
> +const Select = ({ label, placeholder, options, chooseOption, active }) => {
Prefer to use `onChange` callback name instead of `chooseOption`. All component events/callbacks should be prefixed with `on`

2021-09-09 05:55 UTC, ok2ju commented on src/components/Select/Select.jsx
> +const Select = ({ label, placeholder, options, chooseOption, active }) => {
You can rename this prop and merge PR by yourself

2021-09-09 06:33 UTC, merged