feature: Add GET spendings query
anastasiya-nd/budget pull request #34
Opened 2021-09-21 17:52 UTC by anastasiya-nd

2021-09-21 18:33 UTC, ok2ju requested changes

2021-09-21 20:12 UTC, anastasiya-nd commented on src/redux/sagas.js
> +import spendings from '../api/api';
> Did you like path like that? `/api/api`?

Should I create index.js?

2021-09-22 15:01 UTC, ok2ju commented on src/redux/sagas.js
> +import spendings from '../api/api';
I hope so

2021-09-22 19:37 UTC, anastasiya-nd commented on src/redux/actions.js
> +export const getSpendings = (spendings, pagination) => { //eslint-disable-line
> As I mentioned below, for actions that make network requests in most cases it's common practice to have 3 types of one action (_PENDING, _SUCCESS, _ERROR). So, the same logic applies here. There will be 3 action creators: `requestSpendingsPendings`, `requestSpendingsSuccess`, `requestSpendingsError`.

Am I thinking correctly: 
-'getSpendings' has to be 'requestSpendingsSuccess',
-'requestSpendings' has to be 'requestSpendingsPendings'
-and i have to add 'requestSpendingsError' to 'getSpendingsWorker(data)' ?

2021-09-23 05:03 UTC, ok2ju commented on src/redux/actions.js
> +export const getSpendings = (spendings, pagination) => { //eslint-disable-line
Yes, and `requestSpendingsError` will be in the `catch` block accepting `error`

2021-09-23 12:05 UTC, ok2ju requested changes

2021-09-23 12:05 UTC, ok2ju commented on src/redux/reducer.js
> +    case REQUEST_SPENDINGS_SUCCESS:
Why don't you use `REQUEST_SPENDINGS_PENDING` and `REQUEST_SPENDINGS_ERROR` actions here? You can add `loading` filed into `initialState` and show loading screen on your page while request is in process (`REQUEST_SPENDINGS_PENDING`) and hide it when request is finished (`REQUEST_SPENDINGS_SUCCESS`, `REQUEST_SPENDINGS_ERROR`).

2021-09-23 12:05 UTC, ok2ju commented on src/redux/reducer.js
> +        pagination: { ...action.pagination },
If `spendings` is already an array, why do you use spreading here? The same for `pagination`.

2021-09-23 12:05 UTC, ok2ju commented on src/redux/sagas.js
> +import spendings from '../api/api';
You added `index` file but you didn't change import path here.

2021-09-23 12:05 UTC, ok2ju commented on src/redux/sagas.js
> +  yield all([takeEvery(REQUEST_SPENDINGS_PENDING, getSpendingsWorker)]);
You should use `takeLatest` here instead of `takeEvery`.

2021-09-23 12:05 UTC, ok2ju commented on src/redux/types.js
> +export const REQUEST_SPENDINGS_PENDING ='REQUEST_SPENDINGS_PENDING',
Please, define separate export for each variable.

2021-09-25 11:06 UTC, ok2ju approved these changes

2021-09-25 11:06 UTC, merged